---
- hosts: webservers
  become: true
  tasks:
    - name: Stop and disable Apache
      service:
        name: apache2
        state: stopped
        enabled: false

    - name: Uninstall Apache
      apt:
        name: apache2
        state: absent

    - name: Remove HTML page
      file:
        path: /var/www/html/index.html
        state: absent

